# Generated by Django 4.2.5 on 2023-12-05 08:01

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_productrating_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
