# Generated by Django 4.2.5 on 2023-11-21 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_address_zip_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='address',
            new_name='street',
        ),
    ]
