# Generated by Django 4.2.19 on 2025-05-04 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_feedback_alter_basket_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='responded',
            field=models.BooleanField(default=False, verbose_name='Отвечено'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='response',
            field=models.TextField(blank=True, verbose_name='Ответ администратора'),
        ),
    ]
