# Generated by Django 4.2.5 on 2023-11-21 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_user_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='street',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='first_name',
            new_name='user',
        ),
    ]
